services:
  finance-exporter:
    build: .
    container_name: finance-exporter
    restart: on-failure
    ports:
      - "192.168.0.122:7406:7406"
    volumes:
      - ./config.yaml:/usr/src/app/finance-exporter.yaml
    environment:
      - CONFIG=/usr/src/app/finance-exporter.yaml
      - OPTS=-v
